### ISSUE TITLE
CSSRvanka 2000

### ISSUE THREAD

**Issue by Panthevm** [HealthSamurai/xmas-hackathon-2021#5]
# Task 🧙‍♂️

Make a library for Clojure/ClojureScript that allows you to transform CSS during project build, as well as implement a module for it to remove unused CSS 🗑

# Requirements
- [X] Convert CSS to EDN format and back - EDN format to CSS 🙉
- [X] Embed into any project build library 🙊
- [ ] Implement a module for it to remove unused CSS 🙈
- [ ] Сonvenient module 🐵

# Links
### drafts.clj
- https://github.com/Panthevm/clj-ph-css
- https://github.com/Panthevm/compcss
- https://github.com/Panthevm/compcss-clean

### similars.js
- https://github.com/postcss/postcss
- https://github.com/uncss/uncss
